// Writes .oxlint-rules.txt: the full set of rules oxlint is actually running,
// with the version that produced it.
//
// Why this exists: .oxlintrc.json enables the `correctness` CATEGORY rather
// than a list of rules, so the effective rule set is decided by the installed
// oxlint, not by anything in this repo. That is deliberate - see the comment
// on `categories` there - but it means an oxlint bump can start enforcing
// rules nobody asked for, and the first sign of it is a CI failure on a
// Dependabot PR that changed no application code.
//
// This does not prevent that. It makes it legible: with the snapshot committed,
// `npm run lint:rules && git diff` turns "nine mysterious errors" into "this
// bump added react/set-state-in-effect and react/refs". That is the question
// that actually costs time, and GitHub's log makes it worse by stripping rule
// names from the error lines (`##[error]src/App.tsx:214:5: Calling setState...`
// names no rule), so the bare CI output cannot answer it.
//
// Regenerate whenever oxlint moves - as part of the commit that deals with the
// bump. Deliberately NOT enforced in CI: Dependabot cannot regenerate it, so a
// staleness check would force a human push onto every oxlint bump, including
// the ones that merge clean today.
//
// `oxlint --rules` looks like it should do this and emits nothing at all in
// 1.83; `--print-config` is the option that works.

import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(projectRoot, ".oxlint-rules.txt");
const require = createRequire(import.meta.url);

function oxlintVersion() {
  try {
    return require("oxlint/package.json").version;
  } catch {
    return "unknown";
  }
}

// The oxlint binary directly rather than `npx`, which on Windows resolves to a
// shim that would need a shell.
function oxlintBin() {
  const pkgJson = require.resolve("oxlint/package.json");
  return join(dirname(pkgJson), "bin", "oxlint");
}

let raw;
try {
  raw = execFileSync(process.execPath, [oxlintBin(), "--print-config"], {
    cwd: projectRoot,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
} catch (e) {
  console.error(
    `oxlint-rules: could not run \`oxlint --print-config\`.\n` +
      `Run \`npm install\` first. Original error: ${e.message}`
  );
  process.exit(1);
}

let config;
try {
  config = JSON.parse(raw);
} catch {
  // A future oxlint could change or drop --print-config. Fail loudly rather
  // than writing a truncated snapshot that would read as "rules were removed".
  console.error(
    `oxlint-rules: \`oxlint --print-config\` did not return JSON. Its output ` +
      `format has probably changed - check the oxlint release notes and update ` +
      `scripts/oxlint-rules.mjs.`
  );
  process.exit(1);
}

const rules = config.rules ?? {};
const names = Object.keys(rules);

if (names.length === 0) {
  console.error(
    `oxlint-rules: --print-config reported no rules at all, which cannot be ` +
      `right while .oxlintrc.json enables a category. Refusing to write an ` +
      `empty snapshot.`
  );
  process.exit(1);
}

// Sorted, not in --print-config's own order: object key order is not a
// guarantee worth trusting, and an unstable order would produce diff noise
// that buries the one line that matters.
names.sort();

const severityOf = (v) => (Array.isArray(v) ? v[0] : v);

const body = [
  `# Generated by scripts/oxlint-rules.mjs - do not edit by hand.`,
  `# Regenerate with: npm run lint:rules`,
  `#`,
  `# The rules oxlint is actually enforcing, expanded from the categories and`,
  `# rules in .oxlintrc.json. Committed so that an oxlint bump which arms new`,
  `# rules shows up as a diff here instead of only as a CI failure.`,
  `#`,
  `# oxlint ${oxlintVersion()}`,
  `# ${names.length} rules`,
  ``,
  ...names.map((n) => `${n} = ${severityOf(rules[n])}`),
  ``,
].join("\n");

writeFileSync(outFile, body, "utf8");
console.log(`oxlint-rules: .oxlint-rules.txt (oxlint ${oxlintVersion()}, ${names.length} rules)`);
